// SPDX-License-Identifier: GPL-2.0-only

use std::time::Duration;

use thiserror::Error;

/// Nanoseconds in one millisecond, used for readable default construction.
pub const NSEC_PER_MSEC: u64 = 1_000_000;

/// Validated scheduler policy and data-plane limits.
///
/// Values are immutable after BPF attach. Keeping the slice and queue limits in
/// one object ensures the Rust planner and BPF validator receive identical
/// bounds.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SchedulerConfig {
    /// Initial and maximum latency-class request.
    pub latency_slice_ns: u64,
    /// Initial and maximum balanced-class request.
    pub balanced_slice_ns: u64,
    /// Initial throughput-class request; uncontended epochs grow up to the
    /// global bounded maximum.
    pub throughput_slice_ns: u64,
    /// Smallest time slice BPF may accept.
    pub min_slice_ns: u64,
    /// Largest time slice BPF may accept.
    pub max_slice_ns: u64,
    /// Maximum commands generated by one Rust refill pass.
    pub dispatch_batch_limit: usize,
    /// Maximum pool nodes inspected when a head task cannot use a fillable CPU.
    pub placement_scan_limit: usize,
    /// Minimum victim runtime before an SLO dispatch may preempt it.
    pub preemption_min_runtime_ns: u64,
    /// Queueing plus estimated-service target used by the latency SLO gate.
    pub latency_target_ns: u64,
    /// Maximum CPU-time share available to latency selections ahead of root EEVDF.
    pub latency_guarantee_percent: u32,
    /// CPU-time share available to compensate the disruption of urgent preemption.
    pub preemption_budget_percent: u32,
    /// Heartbeat age after which BPF stops depending on userspace decisions.
    pub heartbeat_timeout: Duration,
    /// Maximum sleep between scheduler event-queue polls.
    pub poll_interval: Duration,
    /// Wait threshold that activates one latency-pool rescue selection.
    pub latency_max_wait_ns: u64,
    /// Wait threshold that activates one balanced-pool rescue selection.
    pub balanced_max_wait_ns: u64,
    /// Wait threshold that activates one throughput-pool rescue selection.
    pub throughput_max_wait_ns: u64,
    /// Maximum live task identities retained by the userspace engine.
    pub max_tasks: usize,
    /// Maximum physical nodes across primary and wait-index queues.
    pub max_pool_nodes: usize,
    /// Maximum submitted/running reservations retained at once.
    pub max_reservations: usize,
    /// Bounded Agent/control-thread channel capacity.
    pub control_queue_capacity: usize,
    /// Maximum JSON envelope bytes accepted on the local socket.
    pub max_control_frame_bytes: usize,
    /// Maximum process plus task rows accepted in one Registry batch.
    pub max_snapshot_items: usize,
    /// Successful idempotency responses retained for replay.
    pub response_cache_capacity: usize,
    /// Time an absent Agent is tolerated before controlled detach.
    pub agent_exit_grace: Duration,
}

impl Default for SchedulerConfig {
    /// Builds 1/4/8 ms request ceilings and bounded refill defaults.
    fn default() -> Self {
        Self {
            latency_slice_ns: NSEC_PER_MSEC,
            balanced_slice_ns: 4 * NSEC_PER_MSEC,
            throughput_slice_ns: 8 * NSEC_PER_MSEC,
            min_slice_ns: 250_000,
            max_slice_ns: 64 * NSEC_PER_MSEC,
            dispatch_batch_limit: 64,
            placement_scan_limit: 8,
            preemption_min_runtime_ns: 250_000,
            latency_target_ns: 2 * NSEC_PER_MSEC,
            latency_guarantee_percent: 10,
            preemption_budget_percent: 2,
            heartbeat_timeout: Duration::from_millis(250),
            poll_interval: Duration::from_millis(1),
            latency_max_wait_ns: 10 * NSEC_PER_MSEC,
            balanced_max_wait_ns: 50 * NSEC_PER_MSEC,
            throughput_max_wait_ns: 200 * NSEC_PER_MSEC,
            max_tasks: 65_536,
            max_pool_nodes: 524_288,
            max_reservations: 4_096,
            control_queue_capacity: 1_024,
            max_control_frame_bytes: 1024 * 1024,
            max_snapshot_items: 256,
            response_cache_capacity: 4_096,
            agent_exit_grace: Duration::from_secs(2),
        }
    }
}

impl SchedulerConfig {
    /// Verifies cross-field constraints before any BPF object is opened.
    pub fn validate(&self) -> Result<(), ConfigError> {
        if self.min_slice_ns == 0 || self.min_slice_ns > self.max_slice_ns {
            return Err(ConfigError::SliceBounds);
        }

        for (name, value) in [
            ("latency", self.latency_slice_ns),
            ("balanced", self.balanced_slice_ns),
            ("throughput", self.throughput_slice_ns),
        ] {
            if !(self.min_slice_ns..=self.max_slice_ns).contains(&value) {
                return Err(ConfigError::ClassSlice { class: name, value });
            }
        }

        if self.dispatch_batch_limit == 0 || self.dispatch_batch_limit > 64 {
            return Err(ConfigError::DispatchBatch);
        }
        if self.placement_scan_limit == 0 || self.preemption_min_runtime_ns == 0 {
            return Err(ConfigError::PlacementScan);
        }
        if self.latency_target_ns < self.min_slice_ns
            || !(1..=100).contains(&self.latency_guarantee_percent)
            || !(1..=100).contains(&self.preemption_budget_percent)
        {
            return Err(ConfigError::LatencyAdmission);
        }
        if self.heartbeat_timeout.is_zero() || self.poll_interval.is_zero() {
            return Err(ConfigError::Timing);
        }
        if self.poll_interval >= self.heartbeat_timeout {
            return Err(ConfigError::HeartbeatMargin);
        }
        if self.latency_max_wait_ns == 0
            || self.balanced_max_wait_ns == 0
            || self.throughput_max_wait_ns == 0
        {
            return Err(ConfigError::MaxWait);
        }
        if !(1..=65_536).contains(&self.max_tasks)
            || self.max_pool_nodes < self.max_tasks.saturating_mul(2)
            || self.max_reservations == 0
        {
            return Err(ConfigError::RuntimeCapacity);
        }
        if self.control_queue_capacity == 0
            || !(256..=u32::MAX as usize).contains(&self.max_control_frame_bytes)
            || self.max_snapshot_items == 0
            || self.response_cache_capacity == 0
        {
            return Err(ConfigError::ControlCapacity);
        }
        if self.agent_exit_grace.is_zero() {
            return Err(ConfigError::AgentGrace);
        }

        Ok(())
    }

    /// Returns the configured initial and maximum request for a class.
    pub const fn slice_for(&self, class: crate::identity::TaskClass) -> u64 {
        match class {
            crate::identity::TaskClass::Latency => self.latency_slice_ns,
            crate::identity::TaskClass::Balanced => self.balanced_slice_ns,
            crate::identity::TaskClass::Throughput => self.throughput_slice_ns,
        }
    }

    /// Returns the smallest useful adaptive request for a workload class.
    pub fn min_request_for(&self, class: crate::identity::TaskClass) -> u64 {
        match class {
            crate::identity::TaskClass::Latency => self.min_slice_ns,
            crate::identity::TaskClass::Balanced => self.balanced_slice_ns.min(500_000),
            crate::identity::TaskClass::Throughput => {
                self.throughput_slice_ns.min(2 * NSEC_PER_MSEC)
            }
        }
    }

    /// Adds class-specific headroom to measured service while preserving bounds.
    pub fn request_for_estimate(&self, class: crate::identity::TaskClass, estimate_ns: u64) -> u64 {
        let estimate_ns = if estimate_ns == 0 {
            self.slice_for(class)
        } else {
            estimate_ns
        };
        let request_ns = match class {
            crate::identity::TaskClass::Latency => estimate_ns.saturating_mul(2),
            crate::identity::TaskClass::Balanced | crate::identity::TaskClass::Throughput => {
                estimate_ns.saturating_add(estimate_ns / 4)
            }
        };
        request_ns.clamp(self.min_request_for(class), self.slice_for(class))
    }

    /// Returns the bounded max-wait rescue threshold for a class.
    pub const fn max_wait_for(&self, class: crate::identity::TaskClass) -> u64 {
        match class {
            crate::identity::TaskClass::Latency => self.latency_max_wait_ns,
            crate::identity::TaskClass::Balanced => self.balanced_max_wait_ns,
            crate::identity::TaskClass::Throughput => self.throughput_max_wait_ns,
        }
    }
}

/// Actionable configuration validation failures.
#[derive(Clone, Debug, Error, Eq, PartialEq)]
pub enum ConfigError {
    /// Minimum and maximum slice bounds are inconsistent.
    #[error("min_slice_ns must be non-zero and no larger than max_slice_ns")]
    SliceBounds,
    /// A class slice falls outside the globally accepted range.
    #[error("{class} slice {value} ns is outside the configured slice bounds")]
    ClassSlice {
        /// Name of the invalid class.
        class: &'static str,
        /// Invalid slice value in nanoseconds.
        value: u64,
    },
    /// BPF has a verifier-bounded maximum command batch of 64.
    #[error("dispatch_batch_limit must be in 1..=64")]
    DispatchBatch,
    /// Placement must inspect at least one pool node.
    #[error("placement_scan_limit and preemption_min_runtime_ns must be non-zero")]
    PlacementScan,
    /// Latency admission needs a meaningful target and bounded share.
    #[error("latency_target_ns must cover the minimum slice and admission percentages must be in 1..=100")]
    LatencyAdmission,
    /// Poll and heartbeat durations must both be non-zero.
    #[error("poll_interval and heartbeat_timeout must be non-zero")]
    Timing,
    /// Polling must refresh the heartbeat before it can expire.
    #[error("poll_interval must be shorter than heartbeat_timeout")]
    HeartbeatMargin,
    /// Rescue thresholds must be positive to keep their comparison meaningful.
    #[error("all class max-wait thresholds must be non-zero")]
    MaxWait,
    /// Runtime task, pool, or reservation bounds are inconsistent.
    #[error("max_tasks must fit the BPF map, pool nodes must cover two indexes per task, and reservations must be positive")]
    RuntimeCapacity,
    /// Control transport and replay bounds are invalid.
    #[error("control queue/frame/snapshot/response-cache limits are invalid")]
    ControlCapacity,
    /// Agent exit detection must allow a non-zero grace interval.
    #[error("agent_exit_grace must be non-zero")]
    AgentGrace,
}

#[cfg(test)]
mod tests {
    use super::{ConfigError, SchedulerConfig};

    /// The shipped defaults must always be internally consistent.
    #[test]
    fn defaults_validate() {
        assert_eq!(SchedulerConfig::default().validate(), Ok(()));
    }

    /// Class slices are constrained by the same bounds used in BPF.
    #[test]
    fn rejects_slice_outside_global_bounds() {
        let mut config = SchedulerConfig::default();
        config.latency_slice_ns = config.min_slice_ns - 1;
        assert!(matches!(
            config.validate(),
            Err(ConfigError::ClassSlice {
                class: "latency",
                ..
            })
        ));
    }

    #[test]
    fn adaptive_requests_keep_class_specific_bounds() {
        let config = SchedulerConfig::default();
        assert_eq!(
            config.request_for_estimate(crate::identity::TaskClass::Latency, 100_000),
            250_000
        );
        assert_eq!(
            config.request_for_estimate(crate::identity::TaskClass::Latency, 500_000),
            1_000_000
        );
        assert_eq!(
            config.request_for_estimate(crate::identity::TaskClass::Balanced, 600_000),
            750_000
        );
        assert_eq!(
            config.request_for_estimate(crate::identity::TaskClass::Throughput, 20_000_000),
            8_000_000
        );
    }
}
